version: '3.7'
services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 5050 --reload
    restart: always
    volumes:
      - .:/usr/src/app
    ports:
      - "5050:5050"
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - minio

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine

  minio:
    image: minio/minio
    command: server /data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - "9000:9000"

  celery:
    build: .
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - .env

volumes:
  postgres_data:
